version: '2'

services:
  concourse-db:
    image: postgres
    environment:
    - POSTGRES_DB=concourse
    - POSTGRES_PASSWORD=${CONCOURSE_POSTGRES_PASSWORD}
    - POSTGRES_USER=${CONCOURSE_POSTGRES_USER}
    - PGDATA=/database

  concourse-web:
    image: ${PRIVATE_REPOSITORY}/concourse-web:${CONCOURSE_VERSION}
    command: web
    links: [concourse-db]
    depends_on: [concourse-db]
    ports:
    - 8080:8080
    expose: 
    - 2222
    environment:
    - CONCOURSE_POSTGRES_HOST=concourse-db
    - CONCOURSE_POSTGRES_USER=${CONCOURSE_POSTGRES_USER}
    - CONCOURSE_POSTGRES_PASSWORD=${CONCOURSE_POSTGRES_PASSWORD}
    - CONCOURSE_POSTGRES_DATABASE=concourse
    - CONCOURSE_EXTERNAL_URL=${CONCOURSE_EXTERNAL_URL}
    - CONCOURSE_ADD_LOCAL_USER=admin:${CONCOURSE_LOCAL_USER_PASSWORD}
#    - CONCOURSE_MAIN_TEAM_ALLOW_ALL_USERS=true
    - CONCOURSE_MAIN_TEAM_LOCAL_USER=admin

  concourse-worker:
    image: ${PRIVATE_REPOSITORY}/concourse-worker:${CONCOURSE_VERSION}
    command: worker
    privileged: true
    links: [concourse-web]
    depends_on: [concourse-web]
    environment:
    - CONCOURSE_TSA_HOST=concourse-web:2222
    - CONCOURSE_GARDEN_NETWORK
    scale: 4
