version: '2'

volumes:
  postgres-data:

services:
  postgres:
    image: postgres
    volumes:
    - postgres-data:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=concourse
    - POSTGRES_USER=${CONCOURSE_POSTGRES_USER}
    - POSTGRES_PASSWORD=${CONCOURSE_POSTGRES_PASSWORD}

  web:
    image: ${PRIVATE_REPOSITORY}/concourse-web:${CONCOURSE_VERSION}
    command: web
    depends_on: [postgres]
    links:
    - postgres
    ports:
    - 8080:8080
    expose:
    - 2222
    environment:
    - CONCOURSE_POSTGRES_HOST=postgres
    - CONCOURSE_POSTGRES_USER=${CONCOURSE_POSTGRES_USER}
    - CONCOURSE_POSTGRES_PASSWORD=${CONCOURSE_POSTGRES_PASSWORD}
    - CONCOURSE_POSTGRES_DATABASE=concourse
    - CONCOURSE_EXTERNAL_URL=${CONCOURSE_EXTERNAL_URL}
    # GitHub auth
    - CONCOURSE_GITHUB_CLIENT_ID=${CONCOURSE_GITHUB_CLIENT_ID}
    - CONCOURSE_GITHUB_CLIENT_SECRET=${CONCOURSE_GITHUB_CLIENT_SECRET}
    - CONCOURSE_MAIN_TEAM_GITHUB_TEAM=${CONCOURSE_MAIN_TEAM_GITHUB_TEAM}
    # BitBucket Cloud auth
    #- CONCOURSE_BITBUCKET_CLOUD_CLIENT_ID=${CONCOURSE_BITBUCKET_CLOUD_CLIENT_ID}
    #- CONCOURSE_BITBUCKET_CLOUD_CLIENT_SECRET=${CONCOURSE_BITBUCKET_CLOUD_CLIENT_SECRET}
    #- CONCOURSE_MAIN_TEAM_BITBUCKET_CLOUD_TEAM=${CONCOURSE_MAIN_TEAM_BITBUCKET_CLOUD_TEAM}
    - CONCOURSE_DEFAULT_BUILD_LOGS_TO_RETAIN=10

  worker:
    image: ${PRIVATE_REPOSITORY}/concourse-worker:${CONCOURSE_VERSION}
    command: worker
    privileged: true
    depends_on: [web]
    links:
    - web
    environment:
    # default from 7.1.0
    - CONCOURSE_RUNTIME=containerd
    - CONCOURSE_TSA_HOST=web:2222
    - CONCOURSE_BAGGAGECLAIM_DRIVER=btrfs
    - CONCOURSE_LOG_LEVEL=error
    - CONCOURSE_BAGGAGECLAIM_LOG_LEVEL=info
    # default before 7.1.0
    # - CONCOURSE_RUNTIME=guardian
    # - CONCOURSE_GARDEN_NETWORK
    # - CONCOURSE_GARDEN_LOG_LEVEL=error
    scale: 2
