version: '2'

services:
  db:
    image: postgres
    environment:
    - POSTGRES_DB=concourse
    - POSTGRES_PASSWORD=${CONCOURSE_POSTGRES_PASSWORD}
    - POSTGRES_USER=${CONCOURSE_POSTGRES_USER}
    - PGDATA=/database

  web:
    image: ${PRIVATE_REPOSITORY}/concourse-web:${CONCOURSE_VERSION}
    command: web
    links: [db]
    depends_on: [db]
    ports:
    - 8080:8080
    expose:
    - 2222
    environment:
    - CONCOURSE_POSTGRES_HOST=db
    - CONCOURSE_POSTGRES_USER=${CONCOURSE_POSTGRES_USER}
    - CONCOURSE_POSTGRES_PASSWORD=${CONCOURSE_POSTGRES_PASSWORD}
    - CONCOURSE_POSTGRES_DATABASE=concourse
    - CONCOURSE_EXTERNAL_URL=${CONCOURSE_EXTERNAL_URL}
    # GitHub auth
    - CONCOURSE_GITHUB_CLIENT_ID=${CONCOURSE_GITHUB_CLIENT_ID}
    - CONCOURSE_GITHUB_CLIENT_SECRET=${CONCOURSE_GITHUB_CLIENT_SECRET}
    - CONCOURSE_MAIN_TEAM_GITHUB_TEAM=${CONCOURSE_MAIN_TEAM_GITHUB_TEAM}
    # BitBucket Cloud auth
    #- CONCOURSE_BITBUCKET_CLOUD_CLIENT_ID=${CONCOURSE_BITBUCKET_CLOUD_CLIENT_ID}
    #- CONCOURSE_BITBUCKET_CLOUD_CLIENT_SECRET=${CONCOURSE_BITBUCKET_CLOUD_CLIENT_SECRET}
    #- CONCOURSE_MAIN_TEAM_BITBUCKET_CLOUD_TEAM=${CONCOURSE_MAIN_TEAM_BITBUCKET_CLOUD_TEAM}
    - CONCOURSE_DEFAULT_BUILD_LOGS_TO_RETAIN=10

  worker:
    image: ${PRIVATE_REPOSITORY}/concourse-worker:${CONCOURSE_VERSION}
    command: worker
    privileged: true
    links: [web]
    depends_on: [web]
    environment:
    - CONCOURSE_TSA_HOST=web:2222
    - CONCOURSE_GARDEN_NETWORK
    - CONCOURSE_BAGGAGECLAIM_DRIVER=btrfs
    - CONCOURSE_LOG_LEVEL=error
    - CONCOURSE_GARDEN_LOG_LEVEL=error
    - CONCOURSE_BAGGAGECLAIM_LOG_LEVEL=info
    scale: 2
